workflows:
  android-assistant:
    name: AI Assistant Build
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.tejaretnou.aiassistant"
        APP_NAME: "AI Assistant"
    scripts:
      - name: Set up Android SDK
        script: |
          sdkmanager "platforms;android-34"
          sdkmanager "build-tools;34.0.0"
      - name: Set up signing
        script: |
          mkdir -p $HOME/.android
          echo $CM_KEYSTORE | base64 --decode > $HOME/.android/keystore.jks
          echo "storeFile=$HOME/.android/keystore.jks" > keystore.properties
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> keystore.properties
      - name: Build project
        script: |
          ./gradlew clean assembleDebug
      - name: Run tests
        script: |
          ./gradlew test
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
