workflows:
  android-assistant:
    name: AI Assistant Build
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.tejaretnou.aiassistant"
    scripts:
      - name: Build App
        script: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
